version: '2'

networks:
  byfn:

services:

    kafka0.ispa.com:
      image: hyperledger/fabric-kafka
      container_name: kafka0
      environment:
          - KAFKA_BROKER_ID=0
          - KAFKA_ADVERTISED_PORT=9092  
          - KAFKA_ADVERTISED_HOST_NAME=kafka0.ispa.com
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.ispa.com:2181,zookeeper1.ispa.com:2181,zookeeper2.ispa.com:2181
          - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
          - KAFKA_LOG_RETENTION_MS=-1
          - KAFKA_MESSAGE_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=203809024
          - KAFKA_DEFAULT_REPLICATION_FACTOR=3
          - KAFKA_MIN_INSYNC_REPLICAS=2
          - KAFKA_NUM_REPLICA_FETCHERS=1
      volumes:
          - /apps/opt/bcdata/kafka0/kafka-logs:/tmp/kafka-logs
      ports:
          - "9092:9092"
      networks:
          - byfn

    kafka1.ispa.com:
      image: hyperledger/fabric-kafka
      container_name: kafka1
      environment:
          - KAFKA_BROKER_ID=1
          - KAFKA_ADVERTISED_PORT=9092
          - KAFKA_ADVERTISED_HOST_NAME=kafka1.ispa.com
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.ispa.com:2181,zookeeper1.ispa.com:2181,zookeeper2.ispa.com:2181
          - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
          - KAFKA_LOG_RETENTION_MS=-1
          - KAFKA_MESSAGE_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=203809024
          - KAFKA_DEFAULT_REPLICATION_FACTOR=3
          - KAFKA_MIN_INSYNC_REPLICAS=2
          - KAFKA_NUM_REPLICA_FETCHERS=1
      volumes:
          - /apps/opt/bcdata/kafka1/kafka-logs:/tmp/kafka-logs
      ports:
          - "9093:9092"
      networks:
          - byfn

    kafka2.ispa.com:
      image: hyperledger/fabric-kafka
      container_name: kafka2
      environment:
          - KAFKA_BROKER_ID=2
          - KAFKA_ADVERTISED_PORT=9092
          - KAFKA_ADVERTISED_HOST_NAME=kafka2.ispa.com
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.ispa.com:2181,zookeeper1.ispa.com:2181,zookeeper2.ispa.com:2181
          - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
          - KAFKA_LOG_RETENTION_MS=-1
          - KAFKA_MESSAGE_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=203809024
          - KAFKA_DEFAULT_REPLICATION_FACTOR=3
          - KAFKA_MIN_INSYNC_REPLICAS=2
          - KAFKA_NUM_REPLICA_FETCHERS=1
      volumes:
          - /apps/opt/bcdata/kafka2/kafka-logs:/tmp/kafka-logs
      ports:
          - "9094:9092"
      networks:
          - byfn

    kafka3.ispa.com:
      image: hyperledger/fabric-kafka
      container_name: kafka3
      environment:
          - KAFKA_BROKER_ID=3
          - KAFKA_ADVERTISED_PORT=9092
          - KAFKA_ADVERTISED_HOST_NAME=kafka3.ispa.com
          - KAFKA_ZOOKEEPER_CONNECT=zookeeper0.ispa.com:2181,zookeeper1.ispa.com:2181,zookeeper2.ispa.com:2181
          - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
          - KAFKA_LOG_RETENTION_MS=-1
          - KAFKA_MESSAGE_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_MAX_BYTES=203809024
          - KAFKA_REPLICA_FETCH_RESPONSE_MAX_BYTES=203809024
          - KAFKA_DEFAULT_REPLICATION_FACTOR=1
          - KAFKA_MIN_INSYNC_REPLICAS=1
          - KAFKA_NUM_REPLICA_FETCHERS=1
      volumes:
          - /apps/opt/bcdata/kafka3/kafka-logs:/tmp/kafka-logs
      ports:
          - "9095:9092"
      networks:
          - byfn
